### ISSUE TITLE
ConcurrentModificationException from multiple add()'s

### ISSUE THREAD

**Issue by ruckc** [twotoasters/clusterkraf#21]
I'm thinking this is from calling add() multiple times back to back... instead of using addAll()

java.util.ConcurrentModificationException 
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569) 
at com.twotoasters.clusterkraf.ClustersBuilder.addAll(ClustersBuilder.java:54) 
at com.twotoasters.clusterkraf.ClusteringTask.doInBackground(ClusteringTask.java:34) 
at com.twotoasters.clusterkraf.ClusteringTask.doInBackground(ClusteringTask.java:1) 
at android.os.AsyncTask$2.call(AsyncTask.java:287) 
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
at java.lang.Thread.run(Thread.java:856)

**Comment by curtpm** [comment]
+1

**Comment by alexkipar** [comment]
the same on numerous addAll call on map scrolling

java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at com.twotoasters.clusterkraf.ClustersBuilder.addAll(ClustersBuilder.java:54)
at com.twotoasters.clusterkraf.ClusteringTask.doInBackground(ClusteringTask.java:34)
at com.twotoasters.clusterkraf.ClusteringTask.doInBackground(ClusteringTask.java:15)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
