### ISSUE TITLE
NullPointerException in sample app ToastedMarkerOptionsChooser on certain devices

### ISSUE THREAD

**Issue by carltonwhitehead** [twotoasters/clusterkraf#7]
java.lang.NullPointerException
at android.graphics.Bitmap.copy(Bitmap.java:400)
at com.twotoasters.clusterkraf.sample.ToastedMarkerOptionsChooser.getClusterBitmap(ToastedMarkerOptionsChooser.java:95)
at com.twotoasters.clusterkraf.sample.ToastedMarkerOptionsChooser.choose(ToastedMarkerOptionsChooser.java:67)
at com.twotoasters.clusterkraf.ClusterTransitionsAnimation.addMarker(ClusterTransitionsAnimation.java:243)
at com.twotoasters.clusterkraf.ClusterTransitionsAnimation.onAnimationStart(ClusterTransitionsAnimation.java:201)
at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:937)
at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:951)
at com.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:385)
at com.twotoasters.clusterkraf.ClusterTransitionsAnimation.animate(ClusterTransitionsAnimation.java:52)
at com.twotoasters.clusterkraf.Clusterkraf.transitionClusters(Clusterkraf.java:175)
at com.twotoasters.clusterkraf.Clusterkraf.access$16(Clusterkraf.java:173)
at com.twotoasters.clusterkraf.Clusterkraf$ClusterTransitionsBuildingTaskHost.onClusterTransitionsBuildingTaskPostExecute(Clusterkraf.java:506)
at com.twotoasters.clusterkraf.ClusterTransitionsBuildingTask.onPostExecute(ClusterTransitionsBuildingTask.java:53)
at com.twotoasters.clusterkraf.ClusterTransitionsBuildingTask.onPostExecute(ClusterTransitionsBuildingTask.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:417)
at android.os.AsyncTask.access$300(AsyncTask.java:127)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:143)
at android.app.ActivityThread.main(ActivityThread.java:4914)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)

**Comment by carltonwhitehead** [comment]
This was created in response to the following Google Play crash report:
- Date: May 1, 2013
- Version: 1.0.1
- Device: OTHER
- User Message: force closes immediately upon opening

I have been unable to repeat this issue on any of my test devices. If you are experiencing this issue, please make a comment here with the make/model of your device and the Android OS type (stock or custom firmware) and version.

**Comment by carltonwhitehead** [comment]
In reviewing the API documentation for the calls used near the line referenced in the stack trace, I found only one potential cause for a NullPointerException at that line, and addressed it on my carlton-dev branch.
